settings:
  rootDirectory: ./src
categories:
  - name: Atom
    path: /atom
templates:
  component:
    extensions: []
    files:
      - name: '{{componentName}}.tsx'
        content: |2-

                        import React from 'react';
                        import { I{{componentName}}Props } from './interface';

                        const {{componentName}}: React.FC<I{{componentName}}Props> = ({}) => {
                          return <div>{{componentName}}</div>;
                        };

                        export default {{componentName}};
                      
      - name: interface.ts
        content: export interface I{{componentName}}Props {};
      - name: index.ts
        content: |2-

                        export { default } from './{{componentName}}';
                        export * from './interface';
                      
